### ISSUE TITLE
[BUG] The bot is not responding at all

### ISSUE THREAD

**Issue by Lacapary** [andretkachenko/illuminati-bot#155]
The bot stopped working and did not respond to any commands. We kicked out the bot from the server and invited it again and still is not responding to any of the commands.

![image](https://user-images.githubusercontent.com/7785898/138433229-6e358e70-1440-4333-8c7f-de79d411e00d.png)

**Comment by emanueljrsa** [comment]
With me it hasn't even appeared in the "slash commands", I even tried it with the admin option used in the bot.
Overall it's working, it creates the channels as expected. But I can't change anything because I can't access the commands

**Comment by andretkachenko** [comment]
Hi @emanueljrsa 
Can you please verify that you don't see this menu after you type `/` in the chat?
![image](https://user-images.githubusercontent.com/22518570/139592966-8d3af55d-ad81-46dc-b99c-133390ae49c8.png)

**Comment by emanueljrsa** [comment]
for some reason no, i tried everything
I keep using it, it seems to be a bit punctual with me

![image](https://user-images.githubusercontent.com/71347770/139593298-7b827bef-df19-4c69-ac9c-ac9599fe0e75.png)

**Comment by andretkachenko** [comment]
Can you please take a look at the members who can see the channel (at the right side of your discord app)
There's a chance that the Nexus bot has no permission to view the channel.

**Comment by emanueljrsa** [comment]
![image](https://user-images.githubusercontent.com/71347770/139594080-4468fe70-6098-477d-aa0a-6e83d3862e08.png)
I even tried giving it an administrator

**Comment by andretkachenko** [comment]
That's odd. Did you invite the Nexus bot more than 2-3 months ago?
It might be related to the new permission `Use 
Application commands`. Could you please check `Nexus` role has permission `Use 
Application commands` (see picture) and just to make sure you can also provide `Use 
Application commands` permission at the desired text channel.
It can be also made easier by kicking the bot and inviting it again via the new link in [readme](https://github.com/andretkachenko/nexus-bot#want-to-use-at-your-server). This is due to permission rework made by Discord (now Nexus requires a bigger set of roles than before).

![image](https://user-images.githubusercontent.com/22518570/139594374-4dcdcb80-1799-4366-8079-7feee4852fe0.png)

**Comment by emanueljrsa** [comment]
Oh, it finally worked!
I put it in a little while ago, but it was through top.gg, for some reason it didn't come with the permissions there, I kicked it out and put it again through the link here and it worked!

**Comment by andretkachenko** [comment]
I'll double-check it on top.gg right now, to make sure that the link is valid there. Thank you for the info.
Glad it worked. These new threads and slash commands made a lot of changes for the bot developers, so this kind of misunderstanding will happen anyway.
